[Main]
library=1
IncludeUserRPL=0
AutoLoad=1
Compress=0
Calc48=0
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=test
Config=
ExtPrg=
Message=
Romid=200
Slot=0
Emu48Ram=C:\Users\rober\Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files (x86)\Hewlett-Packard\Debug4x\Emu\default 48GX.bin
Emu49Ram=test.e49
FilePath=AtariDiskEmu.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=new.s
file2=tests.s
file3=imp.s
[Edit]
edit4=>new.s
edit5=imp.s
edit6=tests.s
